### ISSUE TITLE
[CS:S] Icons from "kill info" area are too big / overlapping

### ISSUE THREAD

**Issue by jorgenpt** [ValveSoftware/Source-1-Games#109]
Issue transferred from ValveSoftware/steam-for-linux#1328
@quaec posted at 2013-02-06T19:25:26Z:

The Icons in the "kill info" area\* in the top right corner of the in-game UI are overlapping each other. See the screenshot below

I'm playing at 1680x1050.

Thanks for helping!

*I don't know what the actual name for this is.

![overlapping](https://f.cloud.github.com/assets/233692/132740/d23c0236-7091-11e2-875f-0c8f49c29443.jpg)

``````
Prozessor:
    Hersteller: AuthenticAMD
    Geschwindigkeit: 3200 MHz
    4 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Nicht unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Unterstützt
    SSE41:  Nicht unterstützt
    SSE42:  Nicht unterstützt

Netzwerk-Informationen:
    Netzwerk-Geschwindigkeit: 

Betriebssystem:
    Ubuntu 12.04.2 LTS (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 3.2.0-37-generic
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11103000

Grafikkarte:
    Treiber: NVIDIA Corporation GeForce GTX 260/PCIe/SSE2

    Treiber-Version: 3.3.0 NVIDIA 310.14
    Desktop-Farbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 59 Hz
    Anbieterkennung: 0x10de
    Gerätekennung: 0x5e2
    Anzahl der Monitore: 2
    Anzahl der logischen Grafikkarten: 2
    Prim. Anzeigeauflösung: 1680 x 1050
    Desktop-Auflösung: 2960 x 1050
    Prim. Anzeigegröße: 47,4 cm x 29,6 cm (55,8 cm diag.)

    Primärer Bus: PCI Express 16x
    Primärer VRAM: 896 MB
    Unterstützte MSAA-Modi: 2x 4x 8x 16x 

Soundkarte:
    Audiogerät: SigmaTel STAC9750,51

Speicher:
    RAM: 3953 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    LANG:  de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 928699 MB
    Größter freier Festplattenspeicherblock: 45665 MB

Installierte Software:

Neueste Fehlerberichte:```
``````
