### ISSUE TITLE
[linux] l4d2 not all settings can saved

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/Source-1-Games#2000]
I write about audio settings "speaker". before 6 november update this setting always set to '2 speakers', after update set to '5.1 speakers'
and video setting 'multi-core rendering' always enable
I wont disable multi-core rendering, because with this my PC hands
I played >5000 hours, and every launch I change audio settings, now I change video and audio settings. it's not normal.

**Comment by steamlinux** [comment]
now I try disable Steam Cloud in game setting and in steam settings for l4d2. after re-launch audio and video settings restored (about I said) and Steam Cloud in game setting restored too (enabled)

**Comment by chinoto** [comment]
I have had this same issue with the speaker configuration for a long time, but so far I've just been manually setting it every time I remember to do so, which is getting more bothersome since I'm playing more often.

I tried searching through the configuration files, but I didn't find anything for setting this; the closest I found was `./left4dead2/cfg/config.cfg` with its `snd_*` settings.

I found `snd_surround_speakers "0"`, but L4D2 doesn't recognize it (ran it in console) and it gets deleted from the previously mentioned config file when L4D2 launches. If I had to edit a file and mark it read only to maintain that setting (like I did with https://github.com/ValveSoftware/Source-1-Games/issues/2523), that would be good enough (low standards here 😅).
https://www.reddit.com/r/insurgency/comments/3tmrs2/console_command_for_setting_speakers/

System Specs (YAML highlighting works surprisingly well for this):
```yaml
OS: openSUSE Tumbleweed x86_64 
Host: ROG Strix G513QY_G513QY 1.0 
Kernel: 6.3.7-1-default 
Uptime: 7 days, 14 hours, 26 mins 
Packages: 3590 (rpm), 15 (flatpak) 
Shell: fish 3.6.1 
Resolution: 1920x1080 
DE: Plasma 5.27.5 
WM: KWin 
Theme: Breeze [Plasma], Adwaita [GTK2/3] 
Icons: breeze [Plasma], breeze [GTK2/3] 
Terminal: konsole 
Terminal Font: DejaVu Sans Mono 8 
CPU: AMD Ryzen 9 5900HX with Radeon Graphics (16) @ 3.300GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT 
Memory: 6361MiB / 15376MiB 
```
