### ISSUE TITLE
[TF2/Linux] TF2 fonts do not display on HTML MOTD

### ISSUE THREAD

**Issue by CompyMcKitties** [ValveSoftware/Source-1-Games#524]
Here's the HTML code used to display the TF2 fonts on the MOTD: http://pastebin.com/dkXTxBDd
Screenshot of the MOTD on TF2 Windows - Works as expected http://steamcommunity.com/sharedfiles/filedetails/?id=144001509
Screenshot of the MOTD on TF2 Linux - http://steamcommunity.com/sharedfiles/filedetails/?id=143572818

Server admins can work around this by hosting the TF2 fonts and using @font-face either in the `<style>` tag or the MOTD stylesheet. Example of workaround code:

``` css
@font-face{
    font-family: 'TF2 Professor';
    src: local('☺'), url('tf2professor.ttf') format('truetype');
}
```
